version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  pre_build:
    commands:
      - pip install -r requirements.txt
      - python -m unittest test.py
      - cd frontend
      - npm install
      - npm run build